config/routes.rb
Rails.application.routes.draw do
  root 'menu#index'

  resource :user_session, only: :create
  get    'login',  to: 'user_sessions#new'
  delete 'logout', to: 'user_sessions#destroy'

  get 'menu', to: 'menu#index'
  get 'menu/:index', to: 'menu#show', param: :index, as: :show_menu

  namespace :feature_active_record do
    resources :parents
  end
  namespace :feature_carrier_wave do
    resources :users do
      post :confirm, on: :collection
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feature_active_record.rb
module FeatureActiveRecord
  def self.table_name_prefix
    'feature_active_record_'
  end
end

app/models/feature_active_record/has_many_child.rb
class FeatureActiveRecord::HasManyChild < ApplicationRecord
  belongs_to :parent
end

app/models/feature_active_record/has_one_child.rb
class FeatureActiveRecord::HasOneChild < ApplicationRecord
  belongs_to :parent
end

app/models/feature_active_record/parent.rb
class FeatureActiveRecord::Parent < ApplicationRecord
  has_one :has_one_child, dependent: :destroy
  accepts_nested_attributes_for :has_one_child, allow_destroy: true

  has_many :has_many_children, dependent: :destroy
  accepts_nested_attributes_for :has_many_children, allow_destroy: true
end

app/models/feature_carrier_wave.rb
module FeatureCarrierWave
  def self.table_name_prefix
    'feature_carrier_wave_'
  end
end

app/models/feature_carrier_wave/user.rb
class FeatureCarrierWave::User < ApplicationRecord
  mount_uploader :avatar, FileUploader
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_authentic do |c|
    c.login_field :email
  end
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
  before_action :require_login

  private

  def current_user_session
    return @current_user_session if defined?(@current_user_session)

    @current_user_session = UserSession.find
  end

  def current_user
    return @current_user if defined?(@current_user)

    @current_user = current_user_session&.user
  end

  def require_login
    redirect_to login_url and return false unless logged_in?
  end

  def logged_in?
    !!current_user_session
  end
end

app/controllers/feature_active_record/parents_controller.rb
class FeatureActiveRecord::ParentsController < ApplicationController
  before_action :set_feature_active_record_parent, only: %i[show edit update destroy]

  def index
    @feature_active_record_parents = FeatureActiveRecord::Parent.all.includes(:has_one_child)
  end

  def show; end

  def new
    @feature_active_record_parent = FeatureActiveRecord::Parent.new
  end

  def edit; end

  def create
    @feature_active_record_parent = FeatureActiveRecord::Parent.new(feature_active_record_parent_params)

    if @feature_active_record_parent.save
      redirect_to @feature_active_record_parent, notice: 'Parent was successfully created.'
    else
      render :new
    end
  end

  def update
    if @feature_active_record_parent.update(feature_active_record_parent_params)
      redirect_to @feature_active_record_parent, notice: 'Parent was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @feature_active_record_parent.destroy
    redirect_to feature_active_record_parents_url, notice: 'Parent was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_feature_active_record_parent
    @feature_active_record_parent = FeatureActiveRecord::Parent.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def feature_active_record_parent_params
    params.require(:feature_active_record_parent).permit(
      :name,
      has_one_child_attributes:     %i[id name _destroy],
      has_many_children_attributes: %i[id name _destroy]
    )
  end
end

app/controllers/feature_carrier_wave/users_controller.rb
class FeatureCarrierWave::UsersController < ApplicationController
  before_action :set_feature_carrier_wave_user, only: %i[show edit update destroy]

  def index
    @feature_carrier_wave_users = FeatureCarrierWave::User.all
  end

  def show; end

  def new
    @feature_carrier_wave_user = FeatureCarrierWave::User.new
  end

  def edit; end

  def confirm
    @feature_carrier_wave_user = FeatureCarrierWave::User.new(feature_carrier_wave_user_params)
    @feature_carrier_wave_user.avatar.cache! if feature_carrier_wave_user_params[:avatar]
  end

  def create
    @feature_carrier_wave_user = FeatureCarrierWave::User.new(feature_carrier_wave_user_params)

    if params.dig(:cache, :avatar)&.present?
      @feature_carrier_wave_user.avatar.retrieve_from_cache! params[:cache][:avatar]
    end

    if @feature_carrier_wave_user.save
      redirect_to @feature_carrier_wave_user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  def update
    if @feature_carrier_wave_user.update(feature_carrier_wave_user_params)
      redirect_to @feature_carrier_wave_user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @feature_carrier_wave_user.destroy
    redirect_to feature_carrier_wave_users_url, notice: 'User was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_feature_carrier_wave_user
    @feature_carrier_wave_user = FeatureCarrierWave::User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def feature_carrier_wave_user_params
    params.require(:feature_carrier_wave_user).permit(:name, :avatar)
  end
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  def index
    @menu_items = Menu.items
  end

  def show
    @menu_item = Menu.items[params[:index].to_i]
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new user_session_params.to_h

    if @user_session.save
      redirect_to root_url
    else
      render :new
    end
  end

  def destroy
    current_user_session.destroy
    redirect_to login_url
  end

  private

  def user_session_params
    params.require(:user_session).permit(%i[email password])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feature_active_record/parents_helper.rb
module FeatureActiveRecord::ParentsHelper
end

app/helpers/feature_carrier_wave/users_helper.rb
module FeatureCarrierWave::UsersHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/feature_active_record/parents/_form.html.erb
<%= form_with(model: feature_active_record_parent, local: true) do |form| %>
  <% if feature_active_record_parent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(feature_active_record_parent.errors.count, "error") %> prohibited this feature_active_record_parent from being saved:</h2>

      <ul>
      <% feature_active_record_parent.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>

    <%= label_tag :has_one_child_is_need, 'has one child is need' %>
    <%= check_box_tag :has_one_child_is_need, nil, form.object.has_one_child, onchange: 'setHasOneChildNeed(this.checked)' %>

    <div id="has_one_child_field">
      <%= form.fields_for :has_one_child,
            form.object.has_one_child || FeatureActiveRecord::HasOneChild.new do |has_one_child_field| %>
        <%= has_one_child_field.label :name, 'Has one child name' %>
        <%= has_one_child_field.text_field :name %>

        <%= has_one_child_field.hidden_field :_destroy %>
      <% end %>
    </div>

    <%= form.fields_for :has_many_children do |has_many_child_field| %>
      <%= render 'has_many_child_fields', has_many_child_field: has_many_child_field %>
    <% end %>

    <div id="links">
      <%= link_to_add_association 'add has many child', form, :has_many_children, form_name: :has_many_child_field %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<script>
  /**
   * 対象の表示を切り替える
   *
   * @param String  targetId  表示切替対象のID
   * @param Boolean isVisible 表示有無 表示する場合は `true`
   */
  function setVisible(targetId, isVisible) {
    document.getElementById(targetId).style.display = isVisible ? '' : 'none';
  }

  /**
   * 対象の削除要否を切り替える
   *
   * @param String  targetId  削除要否を持つフィールドのID
   * @param Boolean isDestroy 削除要否 削除する場合は `true`
   */
  function setDestroy(targetId, isDestroy) {
    document.getElementById(targetId).value = isDestroy ? '1' : '0';
  }

  /**
   * 対象の表示及び削除要否を切り替える
   *
   * @paran String  childFieldId        対象の入力欄のID
   * @param String  childDestroyFieldId 対象の削除要否を持つフィールドのID
   * @param Boolean isNeed              対象が必要な場合は `true`
   */
  function setChildNeed(childFieldId, childDestroyFieldId, isNeed) {
    setVisible(childFieldId, isNeed);
    setDestroy(childDestroyFieldId, !isNeed);
  }

  /**
   * has_one_childの表示及び削除要否を切り替える
   *
   * @param Boolean isNeed has_one_childが必要な場合は `true`
   */
  function setHasOneChildNeed(isNeed) {
    setChildNeed(
      'has_one_child_field',
      'feature_active_record_parent_has_one_child_attributes__destroy',
      isNeed
    );
  }

  /**
   * 画面初期化時の処理
   */
  (function (){
    setHasOneChildNeed(<%= !!feature_active_record_parent.has_one_child %>);
  })();
</script>

app/views/feature_active_record/parents/_has_many_child_fields.html.erb
<div class="nested-fields">
  <%= has_many_child_field.label :name, 'Has many child name' %>
  <%= has_many_child_field.text_field :name %>

  <%= link_to_remove_association 'remove has many child', has_many_child_field  %>
</div>

app/views/feature_active_record/parents/edit.html.erb
<h1>Editing Feature Active Record Parent</h1>

<%= render 'form', feature_active_record_parent: @feature_active_record_parent %>

<%= link_to 'Show', @feature_active_record_parent %> |
<%= link_to 'Back', feature_active_record_parents_path %>

app/views/feature_active_record/parents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Feature Active Record Parents</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Has One Child Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feature_active_record_parents.each do |feature_active_record_parent| %>
      <tr>
        <td><%= feature_active_record_parent.name %></td>
        <td><%= feature_active_record_parent.has_one_child&.name %></td>
        <td><%= link_to 'Show', feature_active_record_parent %></td>
        <td><%= link_to 'Edit', edit_feature_active_record_parent_path(feature_active_record_parent) %></td>
        <td><%= link_to 'Destroy', feature_active_record_parent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feature Active Record Parent', new_feature_active_record_parent_path %>

app/views/feature_active_record/parents/new.html.erb
<h1>New Feature Active Record Parent</h1>

<%= render 'form', feature_active_record_parent: @feature_active_record_parent %>

<%= link_to 'Back', feature_active_record_parents_path %>

app/views/feature_active_record/parents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @feature_active_record_parent.name %>
</p>

<p>
  <strong>HasOneChildName:</strong>
  <%= @feature_active_record_parent.has_one_child&.name %>
</p>

<p>
  <strong>HasManyChildName</strong>
  <% @feature_active_record_parent.has_many_children.each do |has_many_child| %>
    <%= has_many_child.name %>
  <% end %>
</p>

<%= link_to 'Edit', edit_feature_active_record_parent_path(@feature_active_record_parent) %> |
<%= link_to 'Back', feature_active_record_parents_path %>

app/views/feature_carrier_wave/users/_form.html.erb
<% action = defined?(post_to) ? { action: post_to} : nil %>

<%= form_with(model: feature_carrier_wave_user, local: true, url: action) do |form| %>
  <% if feature_carrier_wave_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(feature_carrier_wave_user.errors.count, "error") %> prohibited this feature_carrier_wave_user from being saved:</h2>

      <ul>
      <% feature_carrier_wave_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :avatar %>
    <%= form.file_field :avatar %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/feature_carrier_wave/users/confirm.html.erb
<h1>Confirm Feature Carrier Wave User</h1>

<table>
  <tr>
    <th>Name</th>
    <td><%= @feature_carrier_wave_user.name %></td>
  </tr>

  <tr>
    <th>Avatar</th>
    <td><%= @feature_carrier_wave_user.avatar %></td>
  </tr>
</table>

<%= form_with(model: @feature_carrier_wave_user, local: true) do |form| %>
    <%= form.hidden_field :name %>
    <%= hidden_field_tag :"cache[avatar]", form.object.avatar.cache_name %>

    <%= form.submit %>
<% end %>

<%= link_to 'Back', :back %>

app/views/feature_carrier_wave/users/edit.html.erb
<h1>Editing Feature Carrier Wave User</h1>

<%= render 'form', feature_carrier_wave_user: @feature_carrier_wave_user %>

<%= link_to 'Show', @feature_carrier_wave_user %> |
<%= link_to 'Back', feature_carrier_wave_users_path %>

app/views/feature_carrier_wave/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Feature Carrier Wave Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Avatar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feature_carrier_wave_users.each do |feature_carrier_wave_user| %>
      <tr>
        <td><%= feature_carrier_wave_user.name %></td>
        <td><%= feature_carrier_wave_user.avatar %></td>
        <td><%= link_to 'Show', feature_carrier_wave_user %></td>
        <td><%= link_to 'Edit', edit_feature_carrier_wave_user_path(feature_carrier_wave_user) %></td>
        <td><%= link_to 'Destroy', feature_carrier_wave_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feature Carrier Wave User', new_feature_carrier_wave_user_path %>

app/views/feature_carrier_wave/users/new.html.erb
<h1>New Feature Carrier Wave User</h1>

<div style="float: left;">
  <h2>Not via confirm</h2>
  <%= render 'form', feature_carrier_wave_user: @feature_carrier_wave_user %>
</div>

<div style="float: left;">
  <h2>Via confirm</h2>
  <%= render 'form', feature_carrier_wave_user: @feature_carrier_wave_user, post_to: 'confirm' %>
</div>

<div style="clear: both;">
  <%= link_to 'Back', feature_carrier_wave_users_path %>
</div>

app/views/feature_carrier_wave/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @feature_carrier_wave_user.name %>
</p>

<p>
  <strong>Avatar:</strong>
  <%= @feature_carrier_wave_user.avatar %>
</p>

<%= link_to 'Edit', edit_feature_carrier_wave_user_path(@feature_carrier_wave_user) %> |
<%= link_to 'Back', feature_carrier_wave_users_path %>

app/views/menu/index.html.erb
<h1>Menu</h1>

<table>
  <tbody>
    <% @menu_items.each_with_index do |item, index| %>
      <tr>
        <td><%= link_to item.title, show_menu_path(index) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/menu/show.html.erb
<h1><%= @menu_item.title %></h1>

<table class="full_width_table">
  <tr>
    <th>Title: </th>
    <td><%= @menu_item.title %></td>
  </tr>

  <tr>
    <th>Description: </th>
    <td><%= @menu_item.description %></td>
  </tr>

  <tr>
    <th>Demo:</th>
    <td><%= link_to 'デモページ', @menu_item.demo_path %></td>
  </tr>

  <tr>
    <th>Code: </th>
    <td><%= select :menu, :code, @menu_item.codes.map.with_index { |item, index| [item, index] }, include_blank: true %></td>
  </tr>

  <tr>
    <th></th>
    <td><%= text_area_tag 'menu[detail]' %></td>
  </tr>
</table>

<script>
  var codes = [''];
  <% @menu_item.codes.each do |code| %>
    <% code = File.read(Rails.root.join(code)).gsub("\n", '<br />')%>
    codes.push('<%= code %>');
  <% end %>
</script>

app/views/user_sessions/new.html.erb
<%= form_for @user_session, url: user_session_path do |f| %>
  <fieldset>
    <legend>Login</legend>
    <p>
      <%= f.label :email %>
      <%= f.text_field :email %>
    </p>
    <p>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </p>
    <%= f.submit 'Login', class: 'btn btn-primary' %>
  </fieldset>
<% end %>